checks:
  - name: "no-node-affinity"
    disable: true
  - name: "no-readiness-probe"
    disable: true
  - name: "no-liveness-probe"
    disable: true
  - name: "unset-cpu-requirements"
    disable: true
  - name: "unset-memory-requirements"
    disable: true

customChecks: {}

settings:
  includePatterns:
    - "security-configs/**/*.yaml"
  excludePatterns: []
  minSeverity: "warning"

# Report format
report:
  format: "yaml"
  output: "security-report.yaml" 