checks:
  addAllBuiltIn: true
  exclude:
    - "no-node-affinity"  # We're using a test cluster
    - "no-readiness-probe"  # Not needed for test pods
    - "no-liveness-probe"  # Not needed for test pods
    - "unset-cpu-requirements"  # We have default resource limits
    - "unset-memory-requirements"  # We have default resource limits

customChecks: {}

settings:
  includePaths:
    - "security-configs/**/*.yaml"
  excludePaths: []
  minSeverity: "warning"

# Report format
report:
  format: "yaml"
  output: "security-report.yaml" 